/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deu.cse.software2_4.UserLogin;

import deu.cse.software2_4.Order.Chienese_restaurant_info;
import deu.cse.software2_4.Order.Japanese_restaurant_info;
import deu.cse.software2_4.Order.Korean_restaurant_info;
import deu.cse.software2_4.Order.Western_restaurant_info;
import deu.cse.software2_4.OrderList.Orderlist;
import deu.cse.software2_4.Purchase.Purchase_gui;


/**
 *
 * @author 이창희
 */
public class UserloginModel extends javax.swing.JFrame {
    /**
     * Creates new form UserloginModel
     */
    public UserloginModel() {
        initComponents();
        setSize(420, 600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_Korean = new javax.swing.JButton();
        jButton_Chienese = new javax.swing.JButton();
        jButton_Western = new javax.swing.JButton();
        jButton_Japanese = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel1.setText("메뉴/주소 선택");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton_Korean.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jButton_Korean.setText("한식");
        jButton_Korean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_KoreanActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Korean, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 146, 100, 64));

        jButton_Chienese.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jButton_Chienese.setText("중식");
        jButton_Chienese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChieneseActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Chienese, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 146, 100, 64));

        jButton_Western.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jButton_Western.setText("양식");
        jButton_Western.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_WesternActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Western, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 264, 100, 66));

        jButton_Japanese.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jButton_Japanese.setText("일식");
        jButton_Japanese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_JapaneseActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Japanese, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 264, 100, 66));

        jButton_Back.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jButton_Back.setText("뒤로 가기");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 6, -1, -1));

        jButton1.setText("주문 내역");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 370, -1, 46));

        jButton2.setText("결제");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ChieneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChieneseActionPerformed
    
    Chienese_restaurant_info object = new Chienese_restaurant_info();
    object.setVisible(true);
    }//GEN-LAST:event_jButton_ChieneseActionPerformed

    private void jButton_KoreanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KoreanActionPerformed
    Korean_restaurant_info object = new Korean_restaurant_info();
    object.setVisible(true);
    }//GEN-LAST:event_jButton_KoreanActionPerformed

    private void jButton_JapaneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_JapaneseActionPerformed
    
    Japanese_restaurant_info object = new Japanese_restaurant_info();
    object.setVisible(true); 
    }//GEN-LAST:event_jButton_JapaneseActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
    dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_WesternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_WesternActionPerformed
    
    Western_restaurant_info object = new Western_restaurant_info();
    object.setVisible(true); 
    }//GEN-LAST:event_jButton_WesternActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Orderlist object = new Orderlist();
        object.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Purchase_gui purchasegui = new Purchase_gui();
        purchasegui.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserloginModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserloginModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserloginModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserloginModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserloginModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Chienese;
    private javax.swing.JButton jButton_Japanese;
    private javax.swing.JButton jButton_Korean;
    private javax.swing.JButton jButton_Western;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
